pipeline {
    agent any

    stages {
        stage('Build Docker Images') {
            steps {
                script {
                    docker.build('maorsh6/order-service:latest', 'order-service')
                }
            }
        }

        stage('Push Docker Images') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image('maorsh6/user-service:latest').push()
                        docker.image('maorsh6/order-service:latest').push()
                    }
                }
            }
        }

        stage('Deploy with Helm') {
            steps {
                script {
                    sh 'helm upgrade --install user-service ./user-service-chart'
                    sh 'helm upgrade --install order-service ./order-service-chart'
                }
            }
        }
    }
}
